<?php

namespace App\Services;

use App\Models\AbsenceRecord;
use App\Models\AttendanceRecord;
use App\Models\LeaveRequest;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class AbsenceWorkflow
{
    public function save(array $data, User $actor, ?AbsenceRecord $absence = null): AbsenceRecord
    {
        return DB::transaction(function () use ($data, $actor, $absence) {
            $employees = User::whereIn('id', array_filter([$data['employee_id'], $absence?->employee_id]))
                ->orderBy('id')->lockForUpdate()->get();
            $employee = $employees->firstWhere('id', $data['employee_id']);
            $absence = $absence ? AbsenceRecord::lockForUpdate()->findOrFail($absence->id) : new AbsenceRecord;
            $historicalEmployee = $absence->exists && $absence->employee_id === $employee?->id;
            if (! $employee || (! $historicalEmployee && (! $employee->hasRole('employee') || $employee->status === 'Left'))) {
                throw ValidationException::withMessages(['employee_id' => 'Choose a current employee.']);
            }
            if (AbsenceRecord::where('employee_id', $employee->id)->whereDate('date', $data['date'])
                ->when($absence->exists, fn ($q) => $q->whereKeyNot($absence->id))->exists()) {
                throw ValidationException::withMessages(['date' => 'An absence record already exists for this employee on this date.']);
            }
            if (LeaveRequest::where('employee_id', $employee->id)->where('status', 'Approved')
                ->whereDate('from_date', '<=', $data['date'])->whereDate('to_date', '>=', $data['date'])->exists()) {
                throw ValidationException::withMessages(['date' => 'This date overlaps approved leave. Reconcile the leave record before recording an absence.']);
            }
            $attendance = AttendanceRecord::where('employee_id', $employee->id)->whereDate('date', $data['date'])->lockForUpdate()->first();
            if ($attendance && ($attendance->id !== $absence->attendance_record_id) && ! $this->compatible($attendance, $data['absence_type'])) {
                throw ValidationException::withMessages(['date' => 'Conflicting attendance exists on this date. Review that attendance record first.']);
            }
            if ($absence->attendance_record_id && $absence->attendance_record_id !== $attendance?->id) {
                $this->detachAttendance($absence);
            }
            $created = ! $attendance || ($absence->attendance_record_id === $attendance->id && $absence->attendance_created);
            $attendance ??= new AttendanceRecord(['employee_id' => $employee->id, 'date' => $data['date']]);
            $reviewed = ! $data['follow_up_required'];
            $attendance->fill([
                'status' => $data['absence_type'], 'hours' => 0, 'clock_in' => null, 'clock_out' => null, 'work_location' => 'N/A',
                'manager_reviewed' => $reviewed, 'reviewed_by' => $reviewed ? $actor->name : null, 'reviewed_at' => $reviewed ? now() : null,
            ])->save();
            $absence->fill($data + [
                'attendance_record_id' => $attendance->id, 'attendance_created' => $created,
                'reviewed_by' => $actor->name, 'reviewed_at' => now(),
            ])->save();

            return $absence;
        });
    }

    public function delete(AbsenceRecord $absence): void
    {
        DB::transaction(function () use ($absence) {
            User::whereKey($absence->employee_id)->lockForUpdate()->firstOrFail();
            $absence = AbsenceRecord::lockForUpdate()->findOrFail($absence->id);
            $this->detachAttendance($absence);
            $absence->delete();
        });
    }

    public function compatible(AttendanceRecord $attendance, string $type): bool
    {
        return $attendance->status === $type && ! $attendance->clock_in && ! $attendance->clock_out && (float) $attendance->hours === 0.0;
    }

    private function detachAttendance(AbsenceRecord $absence): void
    {
        // Only remove attendance generated by this absence; retain pre-existing records.
        if ($absence->attendance_created && $absence->attendance_record_id) {
            AttendanceRecord::whereKey($absence->attendance_record_id)->delete();
        }
    }
}
