<div class="modal fade" id="attModal" tabindex="-1" aria-hidden="true" aria-labelledby="attModalTitle"><div class="modal-dialog modal-dialog-centered"><div class="modal-content">
<form id="attForm" method="POST" action="{{ route('admin.attendance.store') }}">@csrf <input type="hidden" name="_form" value="attendance"><input type="hidden" name="manager_reviewed" value="1">
<div class="modal-header"><h2 class="modal-title h5" id="attModalTitle">Record Attendance</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
<div class="modal-body"><div class="alert alert-danger d-none" data-form-error role="alert"></div><div class="form-grid-2">
<div class="form-field "><label class="form-label" for="att_employee_id">Employee<span class="required-indicator">*</span></label><select class="form-select" id="att_employee_id" name="employee_id" aria-describedby="att_employee_idError" required>@forelse ($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@empty<option value="">No current employees available</option>@endforelse</select><div class="invalid-feedback-custom" id="att_employee_idError" data-error-for="employee_id"></div></div>
<div class="form-field "><label class="form-label" for="att_date">Date<span class="required-indicator">*</span></label><input type="date" class="form-control" id="att_date" name="date" aria-describedby="att_dateError" required ><div class="invalid-feedback-custom" id="att_dateError" data-error-for="date"></div></div>
<div class="form-field "><label class="form-label" for="att_expected_start">Expected start</label><input type="time" class="form-control" id="att_expected_start" name="expected_start" aria-describedby="att_expected_startError"  value="09:00"><div class="invalid-feedback-custom" id="att_expected_startError" data-error-for="expected_start"></div></div>
<div class="form-field "><label class="form-label" for="att_status">Status<span class="required-indicator">*</span></label><select class="form-select" id="att_status" name="status" aria-describedby="att_statusError" required>@foreach ($statuses as $status)<option>{{ $status }}</option>@endforeach</select><div class="invalid-feedback-custom" id="att_statusError" data-error-for="status"></div></div>
<div class="form-field "><label class="form-label" for="att_clock_in">Clock in</label><input type="time" class="form-control" id="att_clock_in" name="clock_in" aria-describedby="att_clock_inError"  ><div class="invalid-feedback-custom" id="att_clock_inError" data-error-for="clock_in"></div></div>
<div class="form-field "><label class="form-label" for="att_clock_out">Clock out</label><input type="time" class="form-control" id="att_clock_out" name="clock_out" aria-describedby="att_clock_outError"  ><div class="invalid-feedback-custom" id="att_clock_outError" data-error-for="clock_out"></div></div>
<div class="form-field "><label class="form-label" for="att_work_location">Work location</label><select class="form-select" id="att_work_location" name="work_location" aria-describedby="att_work_locationError" ><option>Office</option><option>Remote</option><option>Client Site</option><option>N/A</option></select><div class="invalid-feedback-custom" id="att_work_locationError" data-error-for="work_location"></div></div>
<div class="form-field "><label class="form-label" for="att_hours">Hours</label><input type="number" class="form-control" id="att_hours" name="hours" aria-describedby="att_hoursError"  step="0.5" min="0" max="24" value="8"><div class="invalid-feedback-custom" id="att_hoursError" data-error-for="hours"></div></div>
</div><div class="form-field mt-3"><label class="form-label" for="att_notes">Notes</label><textarea class="form-control" id="att_notes" name="notes" aria-describedby="att_notesError"  rows="2" maxlength="5000"></textarea><div class="invalid-feedback-custom" id="att_notesError" data-error-for="notes"></div></div></div>
<div class="modal-footer"><button type="button" class="btn btn-light-custom" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Save Record</button></div>
</form></div></div></div>
<div class="modal fade" id="absModal" tabindex="-1" aria-hidden="true" aria-labelledby="absModalTitle"><div class="modal-dialog modal-dialog-centered"><div class="modal-content">
<form id="absForm" method="POST" action="{{ route('admin.attendance.absence.store') }}">@csrf <input type="hidden" name="_form" value="absence">
<div class="modal-header"><h2 class="modal-title h5" id="absModalTitle">Record Absence</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div>
<div class="modal-body"><div class="alert alert-danger d-none" data-form-error role="alert"></div><div class="form-grid-2">
<div class="form-field "><label class="form-label" for="abs_employee_id">Employee<span class="required-indicator">*</span></label><select class="form-select" id="abs_employee_id" name="employee_id" aria-describedby="abs_employee_idError" required>@forelse ($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }}</option>@empty<option value="">No current employees available</option>@endforelse</select><div class="invalid-feedback-custom" id="abs_employee_idError" data-error-for="employee_id"></div></div>
<div class="form-field "><label class="form-label" for="abs_date">Date<span class="required-indicator">*</span></label><input type="date" class="form-control" id="abs_date" name="date" aria-describedby="abs_dateError" required ><div class="invalid-feedback-custom" id="abs_dateError" data-error-for="date"></div></div>
<div class="form-field "><label class="form-label" for="abs_absence_type">Absence type<span class="required-indicator">*</span></label><select class="form-select" id="abs_absence_type" name="absence_type" aria-describedby="abs_absence_typeError" required>@foreach ($absenceTypes as $type)<option>{{ $type }}</option>@endforeach</select><div class="invalid-feedback-custom" id="abs_absence_typeError" data-error-for="absence_type"></div></div>
<div class="form-field "><label class="form-label" for="abs_how_reported">How reported</label><input type="text" class="form-control" id="abs_how_reported" name="how_reported" aria-describedby="abs_how_reportedError"  maxlength="255" placeholder="e.g. Phone call, email"><div class="invalid-feedback-custom" id="abs_how_reportedError" data-error-for="how_reported"></div></div>
<div class="form-field "><label class="form-label" for="abs_expected_return">Expected return</label><input type="date" class="form-control" id="abs_expected_return" name="expected_return" aria-describedby="abs_expected_returnError"  ><div class="invalid-feedback-custom" id="abs_expected_returnError" data-error-for="expected_return"></div></div>
<div class="form-field "><label class="form-label" for="abs_reported_to">Reported to</label><input type="text" class="form-control" id="abs_reported_to" name="reported_to" aria-describedby="abs_reported_toError"  maxlength="255" placeholder="e.g. Line manager"><div class="invalid-feedback-custom" id="abs_reported_toError" data-error-for="reported_to"></div></div>
</div>
<div id="absenceReportingDate" class="d-none mt-3"><div class="form-field "><label class="form-label" for="abs_reported_date">Reported date</label><input type="date" class="form-control" id="abs_reported_date" name="reported_date" aria-describedby="abs_reported_dateError"  ><div class="invalid-feedback-custom" id="abs_reported_dateError" data-error-for="reported_date"></div></div></div>
<div class="form-field mt-3"><label class="form-label" for="abs_reason">Reason</label><input type="text" class="form-control" id="abs_reason" name="reason" aria-describedby="abs_reasonError"  maxlength="255"><div class="invalid-feedback-custom" id="abs_reasonError" data-error-for="reason"></div></div>
<div class="mt-3 d-flex gap-4">
<div class="form-field"><div class="form-check"><input class="form-check-input" type="checkbox" name="authorised" value="1" id="absAuthorised" aria-describedby="abs_authorisedError"><label class="form-check-label" for="absAuthorised">Authorised</label></div><div class="invalid-feedback-custom" id="abs_authorisedError" data-error-for="authorised"></div></div>
<div class="form-field"><div class="form-check"><input class="form-check-input" type="checkbox" name="follow_up_required" value="1" id="absFollowUp" aria-describedby="abs_follow_up_requiredError"><label class="form-check-label" for="absFollowUp">Follow-up required</label></div><div class="invalid-feedback-custom" id="abs_follow_up_requiredError" data-error-for="follow_up_required"></div></div>
</div>
<div class="form-field mt-3"><label class="form-label" for="abs_manager_notes">Manager notes</label><textarea class="form-control" id="abs_manager_notes" name="manager_notes" aria-describedby="abs_manager_notesError"  rows="2" maxlength="5000"></textarea><div class="invalid-feedback-custom" id="abs_manager_notesError" data-error-for="manager_notes"></div></div>
<div id="absenceReviewFields" class="d-none mt-3 border-top pt-3">
<div class="form-field "><label class="form-label" for="abs_actual_return">Actual return</label><input type="date" class="form-control" id="abs_actual_return" name="actual_return" aria-describedby="abs_actual_returnError"  ><div class="invalid-feedback-custom" id="abs_actual_returnError" data-error-for="actual_return"></div></div>
<div class="form-text-help mt-2">Clear ?Follow-up required? when the review is complete.</div>
<div class="text-meta mt-2" id="absenceReviewMeta"></div>
</div></div>
<div class="modal-footer"><button type="button" class="btn btn-light-custom" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Save Absence Record</button></div>
</form></div></div></div>
