@extends('layouts.master')

@section('title', 'Add Employee | Bloxt HR')
@section('content')
<div class="page-header-bar"><div class="breadcrumb-trail"><a href="{{ route('admin.employees.index') }}">Employees</a><span class="breadcrumb-sep">/</span>Add Employee</div><h1 class="page-title">Add Employee</h1><p class="page-subtitle">Record a new employee using the standard onboarding workflow.</p></div>
<div class="app-content">@if ($errors->any())<div class="alert alert-danger" role="alert"><strong>Employee was not saved.</strong><ul class="mb-0 mt-2">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<div class="panel" style="max-width:900px;margin:0 auto"><ol class="wizard-steps" id="wizardSteps">@foreach(['Personal','Employment','Compensation','Right to Work','Documents','Review'] as $i=>$step)<li class="wizard-step {{ $i===0?'is-active':'' }}" data-step="{{ $i+1 }}"><span class="wizard-step-index">{{ $i+1 }}</span><span class="wizard-step-label">{{ $step }}</span></li>@if($i<5)<li class="wizard-step-connector"></li>@endif @endforeach</ol>
<form id="wizardForm" method="POST" action="{{ route('admin.employees.store') }}">@csrf
<section class="wizard-panel" data-panel="1"><fieldset class="form-fieldset"><legend class="form-legend">Personal details</legend><div class="form-grid-3"><div class="form-field"><label class="form-label">Employee number*</label><input class="form-control" name="employee_number" required></div><div class="form-field"><label class="form-label">First name*</label><input class="form-control" id="firstName" required></div><div class="form-field"><label class="form-label">Last name*</label><input class="form-control" id="lastName" required></div></div><input name="name" id="fullName" type="hidden"><div class="form-grid-3 mt-3"><div class="form-field"><label class="form-label">Personal email</label><input class="form-control" type="email" name="personal_email"></div><div class="form-field"><label class="form-label">Company email*</label><input class="form-control" type="email" name="email" required></div><div class="form-field"><label class="form-label">Mobile number*</label><input class="form-control" name="phone" required></div></div><div class="form-grid-3 mt-3"><div class="form-field"><label class="form-label">Date of birth</label><input class="form-control" type="date" name="date_of_birth"></div><div class="form-field"><label class="form-label">Nationality</label><input class="form-control" name="nationality"></div><div class="form-field"><label class="form-label">Postcode</label><input class="form-control" name="postcode"></div></div><div class="form-field mt-3"><label class="form-label">Home address</label><input class="form-control" name="address"></div></fieldset><fieldset class="form-fieldset mb-0"><legend class="form-legend">Emergency contact</legend><div class="form-grid-3"><div class="form-field"><label class="form-label">Contact name</label><input class="form-control" name="emergency_contact_name"></div><div class="form-field"><label class="form-label">Relationship</label><input class="form-control" name="emergency_contact_relationship"></div><div class="form-field"><label class="form-label">Contact number</label><input class="form-control" name="emergency_contact_phone"></div></div></fieldset></section>
<section class="wizard-panel d-none" data-panel="2"><fieldset class="form-fieldset mb-0"><legend class="form-legend">Employment details</legend><div class="form-grid-3"><div class="form-field"><label class="form-label">Job title*</label><input class="form-control" name="job_title" required></div><div class="form-field"><label class="form-label">Department*</label><select class="form-select" name="department_id" required>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></div><div class="form-field"><label class="form-label">Manager</label><select class="form-select" name="manager_id"><option value="">No manager (top of structure)</option>@foreach($managers as $manager)<option value="{{ $manager->id }}">{{ $manager->name }}</option>@endforeach</select></div></div><div class="form-grid-3 mt-3"><div class="form-field"><label class="form-label">Employment type*</label><select class="form-select" name="employment_type">@foreach(['Full-time','Part-time','Contract','Temporary'] as $type)<option>{{ $type }}</option>@endforeach</select></div><div class="form-field"><label class="form-label">Start date*</label><input class="form-control" type="date" name="start_date" value="{{ now()->format('Y-m-d') }}" required></div><div class="form-field"><label class="form-label">End date</label><input class="form-control" type="date" name="end_date"></div></div><div class="form-grid-3 mt-3"><div class="form-field"><label class="form-label">Probation end date</label><input class="form-control" type="date" name="probation_end_date"></div><div class="form-field"><label class="form-label">Work location*</label><input class="form-control" name="work_location" required></div><div class="form-field"><label class="form-label">Working arrangement</label><select class="form-select" name="work_arrangement"><option>Office-based</option><option>Hybrid</option><option>Remote</option></select></div></div><div class="form-grid-2 mt-3"><div class="form-field"><label class="form-label">Weekly contracted hours</label><input class="form-control" type="number" step=".5" name="weekly_hours" value="37.5"></div><div class="form-field"><label class="form-label">Normal working hours</label><input class="form-control" name="normal_working_hours" value="09:00-17:30, Monday to Friday"></div></div></fieldset></section>
<section class="wizard-panel d-none" data-panel="3"><fieldset class="form-fieldset mb-0"><legend class="form-legend">Compensation</legend><div class="form-grid-3"><div class="form-field"><label class="form-label">Annual salary (GBP)*</label><input class="form-control" type="number" name="annual_salary" required></div><div class="form-field"><label class="form-label">Salary basis</label><select class="form-select" name="salary_frequency"><option>Annual</option><option>Hourly</option><option>Monthly</option></select></div><div class="form-field"><label class="form-label">Hourly rate</label><input class="form-control" type="number" name="hourly_rate"></div></div><div class="form-grid-3 mt-3"><div class="form-field"><label class="form-label">Effective date*</label><input class="form-control" type="date" name="salary_effective_date" value="{{ now()->format('Y-m-d') }}" required></div><div class="form-field"><label class="form-label">Reason</label><input class="form-control" name="salary_reason" value="Starting salary"></div><div class="form-field"><label class="form-label">Authorised by</label><input class="form-control" name="authorised_by"></div></div></fieldset></section>
<section class="wizard-panel d-none" data-panel="4"><fieldset class="form-fieldset mb-0"><legend class="form-legend">Right to work</legend><p class="form-field mb-3">Right-to-work check required? <label class="ms-2"><input type="radio" name="rtw_required" value="yes" checked> Yes</label><label class="ms-2"><input type="radio" name="rtw_required" value="no"> No</label></p><div id="rtwFields"><div class="form-grid-3"><div class="form-field"><label class="form-label">Check type</label><select class="form-select" name="rtw_check_type"><option>Online Home Office check</option><option>Manual document check</option><option>Other permitted method</option></select></div><div class="form-field"><label class="form-label">Date checked</label><input class="form-control" type="date" name="rtw_check_date" value="{{ now()->format('Y-m-d') }}"></div><div class="form-field"><label class="form-label">Checked by</label><input class="form-control" name="rtw_checked_by"></div></div><div class="form-grid-3 mt-3"><div class="form-field"><label class="form-label">Immigration status</label><input class="form-control" name="immigration_status"></div><div class="form-field"><label class="form-label">Permission start</label><input class="form-control" type="date" name="permission_start"></div><div class="form-field"><label class="form-label">Permission expiry</label><input class="form-control" type="date" name="permission_expiry"></div></div></div></fieldset></section>
<section class="wizard-panel d-none" data-panel="5"><fieldset class="form-fieldset mb-0"><legend class="form-legend">Documents</legend><p class="form-text-help">Record the documents provided for this employee.</p><div id="onboardingDocRows">@foreach(old('document_titles', ['']) as $title)<div class="input-group mb-2"><span class="input-group-text"><i class="bi bi-file-earmark"></i></span><input class="form-control" name="document_titles[]" value="{{ $title }}" maxlength="255" aria-label="Document title" placeholder="e.g. Employment contract signed"><button type="button" class="btn btn-light-custom border" data-remove-document aria-label="Remove document"><i class="bi bi-x"></i></button></div>@endforeach</div><button type="button" class="btn btn-sm btn-outline-primary" id="addOnboardingDocument"><i class="bi bi-plus-lg"></i> Add another document</button></fieldset></section>
<section class="wizard-panel d-none" data-panel="6"><div class="wizard-summary-block"><div class="wizard-summary-title">Review employee record</div><p class="mb-0">Review the information, then confirm and save the employee record.</p></div><label class="form-check mt-4 p-3" style="background:#F5F7FA;border-radius:10px"><input class="form-check-input" type="checkbox" id="confirmAccuracy"> I confirm the information is accurate.</label><input type="hidden" name="status" value="Active"></section>
<div class="form-actions-bar"><button class="btn btn-light-custom d-none" type="button" id="back">Back</button><a class="btn btn-ghost" href="{{ route('admin.employees.index') }}">Cancel</a><button class="btn btn-primary" type="button" id="next">Continue</button><button class="btn btn-primary d-none" type="submit" id="save">Save Employee</button></div></form></div></div>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{let n=1;const f=document.querySelector('#wizardForm'),show=x=>{n=x;document.querySelectorAll('.wizard-panel').forEach(p=>p.classList.toggle('d-none',+p.dataset.panel!==n));document.querySelectorAll('.wizard-step').forEach(s=>{s.classList.toggle('is-active',+s.dataset.step===n);s.classList.toggle('is-complete',+s.dataset.step<n)});back.classList.toggle('d-none',n===1);next.classList.toggle('d-none',n===6);save.classList.toggle('d-none',n!==6)};next.onclick=()=>{const p=document.querySelector(`[data-panel="${n}"]`);if([...p.querySelectorAll('input,select')].every(x=>x.reportValidity()))show(n+1)};back.onclick=()=>show(n-1);f.onsubmit=e=>{fullName.value=[firstName.value,lastName.value].join(' ').trim();if(!confirmAccuracy.checked){e.preventDefault();alert('Please confirm the information is accurate before saving.')}};document.querySelectorAll('[name=rtw_required]').forEach(x=>x.onchange=()=>rtwFields.classList.toggle('d-none',document.querySelector('[name=rtw_required]:checked').value==='no'))})</script>@endpush

@push('scripts')<script>
document.addEventListener('DOMContentLoaded', () => {
 const rows = document.getElementById('onboardingDocRows'), add = document.getElementById('addOnboardingDocument');
 const template = rows.firstElementChild?.cloneNode(true);
 if (!template) return;
 const sync = () => { add.disabled = rows.children.length >= 20; };
 add.addEventListener('click', () => { if (rows.children.length >= 20) return; const row = template.cloneNode(true); row.querySelector('input').value = ''; rows.appendChild(row); row.querySelector('input').focus(); sync(); });
 rows.addEventListener('click', event => { const button = event.target.closest('[data-remove-document]'); if (!button) return; if (rows.children.length === 1) rows.querySelector('input').value = ''; else button.closest('.input-group').remove(); sync(); });
 sync();
});
</script>@endpush
